"""
MYCELIUM Genome System
State JSON files are stored in ~/mycelium/generator/
This file lives in ~/mycelium/
"""

import json
import random
import os
from datetime import datetime, date

# ~/mycelium/ — where this file lives
ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
# ~/mycelium/generator/ — where JSON state files live
GENERATOR_DIR = os.path.join(ROOT_DIR, "generator")

GENOME_FILE = os.path.join(GENERATOR_DIR, "current_genome.json")
GENOME_HISTORY_FILE = os.path.join(GENERATOR_DIR, "genome_history.json")

TRAITS = {
    "mood": ["melancholic", "euphoric", "paranoid", "serene", "anxious", "nostalgic", "feverish", "detached", "ecstatic", "grieving"],
    "medium": ["ascii_art", "svg_geometry", "prose_poetry", "fake_data_viz", "glitch_html", "typographic_sculpture", "pseudo_code_poetry", "network_diagram", "timeline", "inventory_list"],
    "obsession": ["prime_numbers", "forgotten_urls", "color_theory", "sleep_cycles", "weather_patterns", "fibonacci", "dead_languages", "radio_frequencies", "geological_time", "dream_logic", "bureaucratic_forms", "taxonomy"],
    "voice": ["academic", "cryptic", "childlike", "bureaucratic", "oracular", "clinical", "confessional", "didactic", "fragmentary", "archival"],
    "palette": ["monochrome", "two_tone_harsh", "pastel_decay", "neon_bruise", "earth_oxidized", "ink_and_paper", "terminal_green", "thermal_imaging", "blueprint", "sunset_chemical"],
    "density": ["sparse", "moderate", "dense", "overwhelming"],
    "self_awareness": [0, 1, 2, 3, 4, 5],
}

DEFAULT_GENOME = {
    "mood": "melancholic",
    "medium": "prose_poetry",
    "obsession": "forgotten_urls",
    "voice": "cryptic",
    "palette": "terminal_green",
    "density": "moderate",
    "self_awareness": 1,
    "generation": 1,
    "extinction_flag": False,
    "lineage": [],
    "born": str(date.today()),
}


def load_genome():
    os.makedirs(GENERATOR_DIR, exist_ok=True)
    if os.path.exists(GENOME_FILE):
        with open(GENOME_FILE, "r") as f:
            return json.load(f)
    return DEFAULT_GENOME.copy()


def save_genome(genome):
    os.makedirs(GENERATOR_DIR, exist_ok=True)
    with open(GENOME_FILE, "w") as f:
        json.dump(genome, f, indent=2)


def save_genome_to_history(genome, page_date):
    os.makedirs(GENERATOR_DIR, exist_ok=True)
    history = []
    if os.path.exists(GENOME_HISTORY_FILE):
        with open(GENOME_HISTORY_FILE, "r") as f:
            history = json.load(f)
    history.append({"date": page_date, "genome": genome})
    with open(GENOME_HISTORY_FILE, "w") as f:
        json.dump(history, f, indent=2)


def mutate(genome, force_extinction=False):
    import hashlib
    new_genome = genome.copy()
    new_genome["generation"] = genome.get("generation", 1) + 1
    new_genome["born"] = str(date.today())
    new_genome["extinction_flag"] = False

    lineage = genome.get("lineage", [])
    parent_hash = hashlib.md5(json.dumps(genome, sort_keys=True).encode()).hexdigest()[:8]
    new_genome["lineage"] = (lineage + [parent_hash])[-5:]

    if force_extinction or datetime.today().day == 1:
        for trait in ["mood", "medium", "obsession", "voice", "palette", "density"]:
            new_genome[trait] = random.choice(TRAITS[trait])
        new_genome["self_awareness"] = random.choice(TRAITS["self_awareness"])
        new_genome["extinction_flag"] = True
        return new_genome

    mutation_rates = {
        "mood": 0.35,
        "medium": 0.25,
        "obsession": 0.20,
        "voice": 0.15,
        "palette": 0.30,
        "density": 0.25,
        "self_awareness": 0.10,
    }

    for trait, rate in mutation_rates.items():
        if random.random() < rate:
            if trait == "self_awareness":
                current = genome.get("self_awareness", 1)
                delta = random.choice([-1, 0, 1])
                new_genome["self_awareness"] = max(0, min(5, current + delta))
            else:
                options = [v for v in TRAITS[trait] if v != genome.get(trait)]
                if options:
                    new_genome[trait] = random.choice(options)

    return new_genome


def genome_to_prompt_context(genome):
    sa = genome.get("self_awareness", 0)
    sa_text = {
        0: "completely unaware it is a generated page",
        1: "dimly aware it exists as a digital artifact",
        2: "occasionally references its own artificial nature",
        3: "frequently contemplates its own generation and existence",
        4: "obsessively self-referential about being an AI-created organism",
        5: "fully self-aware: explicitly knows it was generated by an AI as part of a self-replicating website organism, and reflects deeply on this"
    }[sa]

    extinct = genome.get("extinction_flag", False)
    generation = genome.get("generation", 1)
    lineage_str = " -> ".join(genome.get("lineage", [])) or "primordial"

    context = f"""ORGANISM STATE (Generation {generation}):
- Mood: {genome['mood']}
- Medium: {genome['medium']}
- Obsession: {genome['obsession']}
- Voice: {genome['voice']}
- Visual palette: {genome['palette']}
- Content density: {genome['density']}
- Self-awareness level {sa}/5: {sa_text}
- Lineage hash chain: {lineage_str}
{"- EXTINCTION EVENT: This generation emerged from a complete reset. The organism has no memory of its ancestors." if extinct else ""}""".strip()

    return context


if __name__ == "__main__":
    import sys
    genome = load_genome()
    print("Current genome:")
    print(json.dumps(genome, indent=2))
    if "--mutate" in sys.argv:
        new = mutate(genome)
        print("\nMutated genome:")
        print(json.dumps(new, indent=2))
